export const CREATE_ORDER = 'CREATE_ORDER'
export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const MANAGE_ORDER = 'MANAGE_ORDER'