export const CREATE_SOLICITATION = 'CREATE_SOLICITATION'
export const LOAD_SOLICITATIONS_SUCCESS = 'LOAD_SOLICITATIONS_SUCCESS'
export const CREATE_SOLICITATION_SUCCESS = 'CREATE_SOLICITATION_SUCCESS'
export const MANAGE_SOLICITATION = 'MANAGE_SOLICITATION'